### ISSUE TITLE
Consider Using Cython/cffi

### ISSUE THREAD

**Issue by danieldjewell** [astronomy/SolTrack#1]
Hi!

I was just playing with some benchmarks ... computing the solar positions for every second of every day in this month (2,592,000 iterations) took only ~1.66s for the C version ... the same thing in Python takes >40s... which isn't surprising.

There are likely massive speed gains if the math is done with Cython/cffi... or even maybe numpy. 

Just a thought :)

**Comment by MarcvdSluys** [comment]
I split of the Python version into a [separate repository](https://github.com/MarcvdSluys/SolTrack-Python), but apparently without updating the link in the README.  Could you please repost your issue [here](https://github.com/MarcvdSluys/SolTrack-Python/issues)?  Apologies for the fuzz...

**Comment by MarcvdSluys** [comment]
SolTrack for Python v0.2.0+ uses Pandas and is up to ~80x faster than before.  You can check it out [here](https://github.com/MarcvdSluys/SolTrack-Python) or [here](https://pypi.org/project/soltrack/).
